series: xenial
description: A nine-machine Kubernetes cluster, appropriate for production. Includes a three-machine etcd cluster and three Kubernetes worker nodes.
machines:
  0:
    constraints: arch=amd64 tags=ceph-osd
  1:
    constraints: arch=amd64 tags=ceph-osd
  2:
    constraints: arch=amd64 tags=ceph-osd
  3:
    constraints: arch=amd64 tags=kubernetes-master
  4:
    constraints: arch=amd64 tags=kubernetes-worker
  5:
    constraints: arch=amd64 tags=kubernetes-worker
services:
  ceph-mon:
    charm: cs:xenial/ceph-mon
    num_units: 3
    options:
      monitor-count: 3
    to:
    - 'lxd:0'
    - 'lxd:1'
    - 'lxd:2'
  ceph-osd:
    charm: cs:xenial/ceph-osd
    num_units: 3
    options:
      #bluestore: true
      #harden: ''
      osd-devices: /dev/vdb
      osd-reformat: 'yes'
    to:
    - '0'
    - '1'
    - '2'
  easyrsa:
    charm: cs:~containers/easyrsa-33
    num_units: 1
    to:
    - '3'
  etcd:
    charm: cs:~containers/etcd-74
    num_units: 1
    to:
    - '3'
  calico:
    charm: cs:~containers/calico-29
    options:
      calico-node-image: quay.io/calico/node:v2.6.5
  kubeapi-load-balancer:
    charm: cs:~containers/kubeapi-load-balancer-55
    expose: true
    num_units: 1
    to:
    - '3'
  kubernetes-master:
    charm: cs:~containers/kubernetes-master-97
    num_units: 1
    options:
      api-extra-args: admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds,NodeRestriction,DefaultStorageClass
      authorization-mode: "RBAC,Node"
      channel: 1.9/stable
    to:
    - '3'
  kubernetes-worker:
    charm: cs:~containers/kubernetes-worker-106
    expose: true
    num_units: 2
    options:
      channel: 1.9/stable
    to:
    - '4'
    - '5'
relations:
- - ceph-osd:mon
  - ceph-mon:osd
- - kubernetes-master
  - ceph-mon
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - calico:etcd
  - etcd:db
- - calico:cni
  - kubernetes-master:cni
- - calico:cni
  - kubernetes-worker:cni
