series: xenial
description: A nine-machine Kubernetes cluster, appropriate for production. Includes a three-machine etcd cluster and three Kubernetes worker nodes.
machines:
  '1':
    constraints: arch=amd64 spaces=internal-api tags=ceph-osd
    series: xenial
  '2':
    constraints: arch=amd64 spaces=internal-api tags=ceph-osd
    series: xenial
  '3':
    constraints: arch=amd64 spaces=internal-api tags=ceph-osd
    series: xenial
  '4':
    constraints: arch=amd64 spaces=internal-api tags=kubernetes-master
    series: xenial
  '5':
    constraints: arch=amd64 spaces=internal-api tags=kubernetes-worker
    series: xenial
  '6':
    constraints: arch=amd64 spaces=internal-api tags=kubernetes-worker
    series: xenial
  '7':
    constraints: arch=amd64 spaces=internal-api tags=kubernetes-worker
    series: xenial
services:
  ceph-mon:
    bindings:
      "": internal-api
    charm: cs:xenial/ceph-mon
    num_units: 3
    to:
    - lxd:1
    - lxd:2
    - lxd:3
  ceph-osd:
    bindings:
      "": internal-api
    charm: cs:xenial/ceph-osd
    num_units: 7
    options:
      bluestore: true
      harden: ''
      osd-devices: /dev/vdb
      osd-reformat: 'yes'
    to:
    - '1'
    - '2'
    - '3'
    - kubernetes-master
    - kubernetes-worker
  easyrsa:
    bindings:
      "": internal-api
    charm: cs:~containers/easyrsa-27
    num_units: 1
    to:
    - '1'
  etcd:
    bindings:
      "": internal-api
    charm: cs:~containers/etcd-63
    num_units: 3
    to:
    - '1'
    - '2'
    - '3'
  flannel:
    charm: cs:~containers/flannel-40
  kubeapi-load-balancer:
    bindings:
      "": internal-api
    charm: cs:~containers/kubeapi-load-balancer-43
    expose: true
    num_units: 1
    to:
    - '4'
  kubernetes-master:
    bindings:
      "": internal-api
    charm: cs:~containers/kubernetes-master-77
    num_units: 1
    options:
      channel: 1.9/stable
    to:
    - '4'
  kubernetes-worker:
    bindings:
      "": internal-api
    charm: cs:~containers/kubernetes-worker-81
    expose: true
    num_units: 3
    options:
      channel: 1.9/stable
    to:
    - '5'
    - '6'
    - '7'
relations:
- - ceph-osd:mon
  - ceph-mon:osd
- - kubernetes-master
  - ceph-mon
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
